name: Replace Text

on: push

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace text
      run: |
        find . -type f -name "*.js" -exec sed -i 's|https://api.openai.com/v1|https://endpoint.cattogpt.repl.co/v1|g' {} \;

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || git commit -am "Made changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
